version: "2"
services:
  app:
    build: ./docker/app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - 'DB_PORT: 3306'
      - 'DB_HOST: database'

  web:
    build: ./docker/web
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
   image: mysql:5.6
   volumes:
     - dbdata:/var/lib/mysql
   ports:
       - 33061:3306
   environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: homestead
         MYSQL_PASSWORD: korea_co
         MYSQL_DATABASE: homestead
#       - 'MYSQL_ROOT_PASSWORD: root'
#       - 'MYSQL_DATABASE: homestead'
#       - 'MYSQL_USER: homestead'
#       - 'MYSQL_PASSWORD: secret'

volumes:
  dbdata:
